apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tektoncd-results-ec5c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tektoncd-results-ec5c
    app.kubernetes.io/part-of: tektoncd-results
    app.kubernetes.io/version: devel
  name: tektoncd-results-ec5c
  namespace: tekton-pipelines
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: rest
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: tektoncd-results-ec5c
    app.kubernetes.io/name: tekton-results-api
status:
  loadBalancer: {}
